<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
  <main>
    <h1><?=$title?></h1>
    <p>A journal for knifing people</p>
  
    <template id="registerFormTemplate">
    <h2>Register</h2>
    <form id="RegisterForm">
    <label for="username">Användare:</label>
      <input type="text" name="username" id="username">
      <label for="password">Lösenord:</label>
      <input type="password" name="password" id="password">
      <button type="submit">Registrera</button>
    </form>
  </template>
  
  </main>

  <div id="testDiv">
    <p id="testPar"></p>
  </div>
  <script type="text/javascript" src="main.js"></script>
  <script src="test.js"></script>
</body>
</html>
